### ISSUE TITLE
help~~~i can't  accured the errors 

### ISSUE THREAD

**Issue by enginy226** [gramaziokohler/abb_irb4600_40_255#1]
run the matlab codes:
robot=importrobot('abb_irb4600_40_255.urdf')

and then comes the errors:

robotics.manip.internal.error(line 19)
   The user supplied inertia element do not constitute a positive semi-definite inertia matrix.

robotics.manip.internal.RigidBody/set.Inertia (line 334)
                robotics.manip.internal.error('rigidbody:InertiaMatrixNotPSD');

robotics.RigidBodyt.Inertia (line 268)
            obj.BodyInternal.Inertia = value;

robotics.manip.internal.Importer/importURDFShared (line 64)
                        body.Inertia = robotics.manip.internal.flattenInertia(Io);

robotics.URDFImporter/importrobot (line 160)
           robot = obj.importURDFShared(model, meshPath, pathToURDF);

importrobot (line 119)
                robot = importer.importrobot(parsedInput.Results.input, param{:});

**Comment by gonzalocasas** [comment]
We don't use matlab for this so, cannot support you much here.
Have you tried updating/removing the inertial elements?

**Comment by enginy226** [comment]
Thanks for your reply~~

Firstly i downloaded the robot models for the ABB Website，and i tried to correct the inertial elements from the datas of the ABB robot models。
But it failed always.

So i tried to check the code every line, and finally found out the why.It's  caused by Ixz。It‘s ’only change the inertial value of Ixz, from '2.7' to below '2.03'. And it works.

**Comment by enginy226** [comment]
Thanks for your reply~~


Firstly i downloaded the robot models for the ABB Website，and i tried to correct the inertial elements from the datas of the ABB robot models。
But it failed always.&nbsp;


So i tried to check the code every line, and finally found out the why.It's&nbsp; caused by Ixz。It‘s ’only change the inertial value of Ixz, from '2.7' to below '2.03'. And it works.








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Gonzalo Casas"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月4日(星期一) 下午4:08
收件人:&nbsp;"gramaziokohler/abb_irb4600_40_255"<abb_irb4600_40_255@noreply.github.com&gt;;
抄送:&nbsp;"燕子"<37918977@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gramaziokohler/abb_irb4600_40_255] help~~~i can't  accured the errors  (#1)





 
We don't use matlab for this so, cannot support you much here.
 Have you tried updating/removing the inertial elements?

**Comment by gonzalocasas** [comment]
@matteo-pacher any thoughts about this? should we change this `2.7` value to `2.03`?

**Comment by enginy226** [comment]
Nothing, i can't figure out the reason。The reason that i change the Ixz's value , it is just because of the robot wrong pose.

**Comment by matteo-pacher** [comment]
As far as I know, the inertia was calculated for the Insitu Fabricator.
I also don't use/know matlab, so I cannot support on that side.
We initially used the URDF in PyBullet for the DeepTimber project, but that did not raise any error related to inertia.

**Comment by gonzalocasas** [comment]
Thanks. In that case, I'll close this.

**Comment by enginy226** [comment]
Thanks a lot.
I will&nbsp;appreciate for&nbsp;your explain about the meaning and connection with URDF and DeepTimber Project? I'm confused about it.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Matteo Pacher"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月6日(星期三) 凌晨0:53
收件人:&nbsp;"gramaziokohler/abb_irb4600_40_255"<abb_irb4600_40_255@noreply.github.com&gt;;
抄送:&nbsp;"燕子"<37918977@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gramaziokohler/abb_irb4600_40_255] help~~~i can't  accured the errors  (#1)





 
As far as I know, the inertia was calculated for the Insitu Fabricator.
 I also don't use/know matlab, so I cannot support on that side.
 We initially used the URDF in PyBullet for the DeepTimber project, but that did not raise any error related to inertia.
