### ISSUE TITLE
abb_irb4600_40_255 joint definition different from ROS-I repo

### ISSUE THREAD

**Issue by yck011522** [gramaziokohler/abb_irb4600_40_255#2]
I was using this repo for a while (passed on to me from @matteo-pacher) and I found that there are some discrepancy between this and the one on ros-industrial : https://github.com/ros-industrial/abb_experimental/blob/kinetic-devel/abb_irb4600_support/urdf/irb4600_40_255_macro.xacro

The link 4+5 length is 1.271m instead of the 1.270 (which is equal to the spec sheet)

https://search.abb.com/library/Download.aspx?DocumentID=3HAC032885-001&LanguageCode=en&DocumentPartId=&Action=Launch

![2021-03-09 12_11_05](https://user-images.githubusercontent.com/1297653/110462109-8e118d80-80d0-11eb-9dca-2bfca372bddf.jpg)

Left is ros-industrial notice joint_5 xyz="1.270 0 0 meaning 1.27 meters distance from elbow to wrist. The right is our rfl urdf look at robot12_joint_4 and robot12_joint_5 they have xyz="0.332 0 0.175" and xyz="0.939 0 0" combined is 0.332 + 0.939 = 1.271
In the spec sheet of the robot, look at line 10/2.55 dimension E, is labeled at 1270. not 1271. So with 1271, my IK / FK / Path Planning was off by one full millimeter.

![2021-03-09 10_30_33](https://user-images.githubusercontent.com/1297653/110461208-6b32a980-80cf-11eb-8bfd-a80d611a4395.jpg)

ROS-I repo joint 4 and 5: 

https://github.com/ros-industrial/abb_experimental/blob/1c964f9facc8ecc52a34ed7604bcd4f8dff498c8/abb_irb4600_support/urdf/irb4600_40_255_macro.xacro#L138-L151

Our repo joint 4 and 5: 
https://github.com/gramaziokohler/abb_irb4600_40_255/blob/219b9f5a2d91b0a60f5200bb5072da903eca2e7b/urdf/abb_irb4600_40_255_macro.xacro#L172-L190

Notice that other joints are also defined differently, particularly `joint_6` axis and `link_6-tool0` origin. Although they are geometrically equivalent.

**Comment by matteo-pacher** [comment]
I did a quick test comparing the MoveIt forward kinematics result to the RobotStudio ones, to confirm the discrepancy that you pointed out:
![210310_screenshot0](https://user-images.githubusercontent.com/32835868/110617655-363d5a00-8196-11eb-8abb-209e478babad.JPG)
This ABB URDF description is off by 1 mm, as you said.
