### ISSUE TITLE
link 6 mesh model where flange are not flush with the ee frame

### ISSUE THREAD

**Issue by yck011522** [gramaziokohler/abb_irb4600_40_255#3]
Comparision make this obvious:

This is the visual (blue) and collision (red) geometry from our repo, notice that the flange frame (red line) is not aligned. The mesh is too long by 2.99mm:
![2021-03-09 12_18_10](https://user-images.githubusercontent.com/1297653/110462994-aa61fa00-80d1-11eb-9ffe-a35f46674aeb.jpg)

Below is the mesh and urdf loaded from ros-industrial (https://github.com/ros-industrial/abb_experimental/blob/kinetic-devel/abb_irb4600_support/urdf/irb4600_40_255_macro.xacro). They align.

![2021-03-09 12_17_57](https://user-images.githubusercontent.com/1297653/110463001-ab932700-80d1-11eb-9654-1906734638f9.jpg)

In case this matters: I used compas_fab in Rhino GH to load these models in case that mattered. I have also converted the visual mesh used in ROS-I from .dae to stl formate to be laoded by compas_fab.

**Comment by matteo-pacher** [comment]
fixed in #4
